# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:32
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correctiv_justizgelder', '0005_auto_20151204_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='search_index',
        ),
        migrations.AddField(
            model_name='fine',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
